### ISSUE TITLE
Help with "Error executing process > 'map_parse_sort_chunks...'

### ISSUE THREAD

**Issue by jmteix** [open2c/distiller-nf#186]
Hi All,

Any ideas about what might be going on here?

Thanks,
JT

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'map_parse_sort_chunks (library:411N run:lane1 chunk:0)'

Caused by:
  Process `map_parse_sort_chunks (library:411N run:lane1 chunk:0)` terminated with an error exit status (1)

Command executed:

  TASK_TMP_DIR=$(mktemp -d -p ./ distiller.tmp.XXXXXXXXXX)
  touch 411N.lane1.hg38.0.bam
  
  bwa mem -t 40  -SP Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa         411NP010_L000_R1_001.fastq.gz 411NP010_L000_R2_001.fastq.gz      | pairtools parse --drop-sam --drop-readid        --add-columns mapq --walks-policy mask       -c hg38.reduced.chrom.sizes       | pairtools sort --nproc 40                      -o 411N.lane1.hg38.0.pairsam.gz                      --tmpdir $TASK_TMP_DIR       | cat
  
  rm -rf $TASK_TMP_DIR

Command exit status:
  1

Command output:
  (empty)

Command error:
  [M::bwa_idx_load_from_disk] read 0 ALT contigs
  [M::process] read 2649008 sequences (400000208 bp)...
  [W::sam_hdr_create] Ignored @SQ SN:KI270330 : bad or missing LN tag
  Traceback (most recent call last):
    File "/miniconda3/bin/pairtools", line 8, in 
      sys.exit(cli())
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/miniconda3/lib/python3.9/site-packages/pairtools/cli/__init__.py", line 183, in wrapper
      return func(*args, **kwargs)
    File "/miniconda3/lib/python3.9/site-packages/pairtools/cli/parse.py", line 165, in parse
      parse_py(
    File "/miniconda3/lib/python3.9/site-packages/pairtools/cli/parse.py", line 244, in parse_py
      sam_chromsizes = headerops.get_chromsizes_from_pysam_header(samheader)
    File "/miniconda3/lib/python3.9/site-packages/pairtools/lib/headerops.py", line 235, in get_chromsizes_from_pysam_header
      chromsizes = [(sq["SN"], int(sq["LN"])) for sq in SQs]
    File "/miniconda3/lib/python3.9/site-packages/pairtools/lib/headerops.py", line 235, in 
      chromsizes = [(sq["SN"], int(sq["LN"])) for sq in SQs]
  KeyError: 'LN'
  WARNING:pairtools:Headerless input, please, add the header by `pairtools header generate` or `pairtools header transfer`
  Traceback (most recent call last):
    File "/miniconda3/bin/pairtools", line 8, in 
      sys.exit(cli())
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/miniconda3/lib/python3.9/site-packages/pairtools/cli/__init__.py", line 183, in wrapper
      return func(*args, **kwargs)
    File "/miniconda3/lib/python3.9/site-packages/pairtools/cli/sort.py", line 70, in sort
      sort_py(pairs_path, output, nproc, tmpdir, memory, compress_program, **kwargs)
    File "/miniconda3/lib/python3.9/site-packages/pairtools/cli/sort.py", line 89, in sort_py
      header = headerops.append_new_pg(header, ID=UTIL_NAME, PN=UTIL_NAME)
    File "/miniconda3/lib/python3.9/site-packages/pairtools/lib/headerops.py", line 346, in append_new_pg
      raise Exception("Input file is not valid .pairs, has no header or is empty.")
  Exception: Input file is not valid .pairs, has no header or is empty.

**Comment by claudiarabu** [comment]
Hi @jmteix , I am getting the same error. Did you solve it? If yes, how? Thanks!

**Comment by jmteix** [comment]
No, I never did.  I moved on to HiC Explorer.  Sorry

**Comment by golobor** [comment]
hi, @claudiarabu ,
from the error message in the original post, I'd suspect that the mapping step has failed, for some reason.
From the top of my head, I can think of two possibilities:
(a) for some reason, the provided bwa index didn't work
(b) the fastq files had some issues, e.g. they had non-matching sequence IDs for R1 and R2.
I would recommend checking the temporary folder of the failed nextflow task and try inspecting all the input files there as executing the mapping command manually.

**Comment by claudiarabu** [comment]
Hi @jmteix, thanks for the quick answer and good luck with your analysis!
 
Hi @golobor ,
Thanks for the suggestion! I executed the command manually (on the cluster) and it worked and even spotted a tiny mistake in a file required by the parse function, so very good. However, it still gives me errors when I run it locally and I am afraid the error is not extremely informative in this case. Unfortunately, I don’t have sudo permissions and cannot install Docker on the cluster, but I will try to run it there using singularity (as it can be installed in a conda env) and keep you updated!
